### ISSUE TITLE
Not working in IntelliJ Idea version 2023.3

### ISSUE THREAD

**Issue by lulunac27a** [ByteAurora/intellij-codexp#11]
I'm using IntelliJ Idea version 2023.3, but the plugin is incompatible: `Plugin 'CodeXP' (version '2.0.0') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IC-233.13135.103`, But it works on version 2023.2.

**Comment by ByteAurora** [comment]
I'm sorry for the late response. 

I have checked the compatibility issue you mentioned and will release a new version as soon as possible :)

**Comment by ByteAurora** [comment]
~~I've checked for compatibility issues and, in CodeXP v2.0.0, removed some APIs that were deprecated to keep up with the new versions of the IntelliJ IDE. This means you won't be able to use the latest version of CodeXP with your current IDE version due to the deprecated APIs in the newer IDE versions.~~

~~Also, future releases of CodeXP might have installation restrictions to ensure compatibility with the latest versions of the IDE. To ensure a stable use of the plugin, I recommend updating your IDE or sticking with a previous version of CodeXP.~~

~~For more details, please see the related patch notes here: [CodeXP v2.0.0 Patch Note](https://byteaurora.github.io/posts/intellij-codexp-v2.0.0/#resolve-compatibility-issues-with-the-latest-ide)~~

I apologize for the misunderstanding regarding the issue you mentioned. I will update and upload a hotfix to ensure compatibility with the latest version.

Thank you for bringing the issue related to the plugin to our attention. :)

**Comment by ByteAurora** [comment]
I have released a new version of the plugin that resolves the issue you mentioned. It is currently under review in the Jetbrains Marketplace, and once the review is complete, you will be able to update it through your IDE.

If you wish to use it sooner, you can download and apply the plugin directly from the Github Release([CodeXP v2.0.1](https://github.com/ByteAurora/intellij-codexp/releases/tag/v2.0.1)).

Thank you for your interest in the plugin.
