### ISSUE TITLE
Action Challenge 을 통해 레벨업하기가 쉽네요 

### ISSUE THREAD

**Issue by Blenbre777** [ByteAurora/intellij-codexp#5]
![image](https://github.com/ILoveGameCoding/intellij-codexp/assets/42365757/72324670-236e-4ba0-bee2-a5c4098ed29e)

If I press "Back" key in the Name field, I will get more experience. Please correct it

**Comment by ByteAurora** [comment]
All actions not defined in CodeXP are counted through Other Actions. If you are continuously pressing Backspace, it is also considered as a specific activity of erasing, so there is no problem with the XP continuously increasing. In addition, the XP will continue to increase because continuous saving or holding down a specific key is also considered an activity. This is consistent with the original intention of the plugin development. 

There might be additions to this feature if the actions are further subdivided in the future, but there are currently no plans to modify this part.
